### ISSUE TITLE
collected_material_photos change image container to state of the art handling

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#559] opened 2020-04-23 18:31 UTC

**Comment by urapadmin** [comment] 2020-04-25 03:46
### @test v8.9.18
needs proper image container testing as well.

**Comment by SamKimball-BrownU** [comment] 2020-05-11 05:14
Issue:

Drag and drop does not lead to warning.

There are no issues with drag and drop in main image container, but in popup it does not actually add the image to the gallery at all.  Drag and drop is a pain, so all I think you need to do is add warning popup.

Other than that, all working as intended.

**Comment by SamKimball-BrownU** [comment] 2020-05-11 05:15
I don't know if this was clear, but drag and drop never leads to popup in collected material photos

**Comment by urapadmin** [comment] 2020-05-11 16:17
if only I could. The issue is I cannot prevent drag and drop from happening. I can only guess that an image arrived due to a drag and drop operation. But at that point it is finished and commited. Filemaker... So I have to attend to it. Just to clarify: This is an issue with the popup here, right? The popups in other image containers are ok (or you would have filed a ticket), right?

**Comment by urapadmin** [comment] 2020-05-11 21:20
### fixed the collected material container in v9.0.4. 
Both the drag & drop message and the handling of the image should now be as expected.

**Comment by SamKimball-BrownU** [comment] 2020-05-14 08:28
So everything is working. The only issue is that the drag and drop warning does not appear when dragging and dropping into not-popup*. However, the image is handled properly, appears in gallery, gets deleted, etc. after drag and drop. Pretty minor issue.


\* it always feels silly to say not-popup... but I can't think of any other name for it....

**Comment by urapadmin** [comment] 2020-05-14 15:59
something I can only reconstruct like this:
If I add a new locus photo record or go to an existing BUT without making the image container the active control, drag & drop leads to the warning. 
If I click on the image container first (making it the active control) and then drag into the container, the message does not appear. The latter is ok but should be the case in the popup as well.

**Comment by urapadmin** [comment] 2020-05-14 16:13
if you see the same behaviour I see, you can close this. Otherwise move it back to me.

**Comment by SamKimball-BrownU** [comment] 2020-05-15 20:31
This is exactly the behavior I observe, therefore closing ticket

**Comment by urapadmin** [comment] 2020-05-17 20:17
reopened because image proxy was not set correctly.

**Comment by urapadmin** [comment] 2020-05-17 23:51
### v9.1
I don't want this filemaker job anymore. I have never wanted it,

**Closed** 2020-05-18 01:54 UTC
Labels: filemaker, test-stage
