### ISSUE TITLE
Weight field disappears for ceramic material type

### ISSUE THREAD

**Issue by mcornacchia25** [urapadmin/kiosk#1273] opened 2021-12-13 19:11 UTC
Created new collected material. Then selected ceramic material type, at which point the weight field disappeared. The same issue occurred for material type animal bone. I was in FileMaker on the purple iPad.

**Comment by urapadmin** [comment] 2021-12-19 20:35
Hy Meghan and thanks for your first ticket. 
What you describe is intended behaviour. If you are logged in as admin and go to the configuration (start page / admin tab, config button), there is a configuration setting under visibility: hide_count_and_weight_for_materials. 

It lists those material types for which the weight is made invisible because such materials are weighed in detail by a specialist in a special module.

**Comment by lbestock** [comment] 2021-12-19 20:54
I forgot that was configurable, too. As I forgot elements of image containers, which resulted in a mess in a recent ticket. Meghan, if I remember correctly you didn't even have registrar status. You should log in as admin so you can a) see the configuration Lutz talks about here, and b) change your own status as a user in Filemaker so you are registrar (you'll be able to edit tags, then). To login to the Filemaker file as admin, you use the super fancy ID "admin" and the even more surprising password "admin".

**Comment by urapadmin** [comment] 2021-12-19 21:32
> I forgot that was configurable, too. As I forgot elements of image containers, which resulted in a mess in a recent ticket. Meghan, if I remember correctly you didn't even have registrar status. You should log in as admin so you can a) see the configuration Lutz talks about here, and b) change your own status as a user in Filemaker so you are registrar (you'll be able to edit tags, then). To login to the Filemaker file as admin, you use the super fancy ID "admin" and the even more surprising password "admin".

just make it a habit to test as a normal user whenever you can because the admin user gets special treatment by the software.

**Comment by mcornacchia25** [comment] 2021-12-20 16:37
I logged in as admin and was able to see that setting and give myself registrar status. I reuploaded and synched and I think it worked. Thanks for your help!

**Comment by urapadmin** [comment] 2021-12-21 19:59
So I close this (something you are welcome to do once you think an issue is done).

**Closed by urapadmin** 2021-12-21 19:59 UTC
Labels: filemaker, user manual
