### ISSUE TITLE
su ceramics: filemaker shows blank panel over UI after inserting an image (error type 1)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1258] opened 2021-11-13 12:43 UTC
This is about the image container in s'Urachi style ceramics. Can be tested when we go back to s'Urachi one day.
- [x] change su_ceramics_add_..to_cache to deferred strategy

**Comment by urapadmin** [comment] 2021-11-13 12:47
### @test 11.6.4
  - [ ] apply image container test method [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=how_to_test_an_image_container#test_of_deferred_file_identifier_cache_handling_version_116_and_higher](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=how_to_test_an_image_container#test_of_deferred_file_identifier_cache_handling_version_116_and_higher) to this

**Comment by lbestock** [comment] 2022-01-03 21:15
I have reconfigured PVD to have s'Urachi style ceramics so I can test this.
Deleting an image using the menu removes the image from the gallery, too, but interestingly not the image container from the gallery. The identifier is gone. I checked that it really was gone both by closing and reopening the file and by using the popup to put an image from the gallery into a new image container. It let me use this image to populate the new image container, with the proxy and everything, but no image. Here is what the gallery looks like:
![image](https://user-images.githubusercontent.com/49291909/147981059-834e1a7e-df68-40ba-82f0-703dfc4e6b9b.png)
Deleting the record using the trash button instead of the image using the menu does the proper thing - image still in gallery, context removed.

**Comment by lbestock** [comment] 2022-01-14 00:25
@mcornacchia25 and @luizaogs - this one is back to us to test as an image container for the image container problems; I've made the other issue its own ticket. BUT this needs a special configuration to test. I did the configuration and synchronized, but you will need a fresh prep and download of your workstations before you can test this.

Hm and it looks like I missed a tiny part in the configuration, but it doesn't matter because there is enough there to do ceramics processing s'Urachi style.

Go to the registrar and specialists tab.
Click ceramics.
You'll get a new form you haven't seen before that is mostly blank with a purple header. In the middle is a gray button that lets you choose which ceramics CM you wish to process. Choose one.
Add a new fragment with the + button.
Now you have two tabs, nicely in Italian for you. You can make Osservazioni if you wish, but you'll find the image container to test under Immagini.

**Comment by lbestock** [comment] 2022-01-14 00:37
(The thing I didn't configure is that only previously made ceramics will pop up for processing. I changed how ceramics are named to be like s'Urachi. If you want to make a new ceramic collected material and for that to be available to process, you can change the missing configuration setting yourself. Log in as admin. Go to the admin tab. Configuration. Visibility. For "show only this material in pottery selection" type "ceramic - diag.")

**Comment by luizaogs** [comment] 2022-01-14 12:02
Besides the deletion problem noted in #1289 this is working for me.

[I once again ran into an issue with changing image descriptions, though (as in #1251). I'm not making it its own ticket yet because I cannot reproduce it reliably nor find a pattern (if you'd like me to do that anyway, just let me know). Noting what happened here for future reference: when I changed the description of the second image in the list it did not change in the gallery. Then I tried adding more images and changed the description of the fourth image, which did change in the gallery. Later going back to the second image and changing that description did work, so it seems similar to the issue I encountered in features.]

**Comment by urapadmin** [comment] 2022-01-14 17:32
### @test 11.6.17
Sorry we have to test this again because of a bug I found. There should be exactly ONE flicker and all should work, of course.

**Comment by luizaogs** [comment] 2022-01-14 20:39
I do get one flicker but I also get the flashing menu -- not sure if you were trying to get rid of that this time around, so I note it here.

**Comment by luizaogs** [comment] 2022-01-14 20:45
The image containers themselves are working here, with persisting issues detailed in #1293 and #1289.

**Comment by mcornacchia25** [comment] 2022-01-14 21:28
Same thing as Luiza with the flashing menu. I did not have issues with changing descriptions, but did have the deletion problem from #1289.

**Comment by lbestock** [comment] 2022-01-14 23:55
Ha this one can't be totally thoroughly tested properly yet so I send it back to you, @urapadmin . There is no popup for an image container in s'U ceramics. One has a delete button and the second button is straight to the gallery, not the usual popup.

**Comment by urapadmin** [comment] 2022-01-15 01:14
> Ha this one can't be totally thoroughly tested properly yet so I send it back to you, @urapadmin . There is no popup for an image container in s'U ceramics. One has a delete button and the second button is straight to the gallery, not the usual popup.

It is true that there is simply no popup here. The reason is that we are already in a popup and I cannot open a popup from a popup.

**Comment by urapadmin** [comment] 2022-01-31 18:17
@lbestock: If you can confirm this is working now, we can close this for the time being. We will be working on it when s'Urachi is on, anyways.

**Comment by urapadmin** [comment] 2022-01-31 18:20
(by the way, this is still about any image errors occuring! It got a bit out of hand here)

**Comment by lbestock** [comment] 2022-01-31 18:26
When one adds a new image container in s'Urachi ceramics photos if there already is one, the new image is not on top. One sees the existing image. Oh wait, it's only if one has added an image description after adding the photo, so familiar problem.

**Comment by lbestock** [comment] 2022-01-31 18:31
No image errors. Now let's see if I can remember how to reconfigure URAP.

**Closed** 2022-01-31 18:46 UTC
Labels: bug, test-stage, filemaker
