### ISSUE TITLE
site note images: filemaker shows blank panel over UI after inserting an image (error type 1)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1256] opened 2021-11-12 23:20 UTC
This here is for the image container in site note photos.

- [x] change add_*_to_cache method to the deferred strategy
- [x] check modified timestamp

**Comment by urapadmin** [comment] 2021-11-13 10:00
### @test 11.6.5
- [ ] apply test scheme for image containers

**Comment by luizaogs** [comment] 2021-11-14 20:51
I'm also getting the flashing menu here between flickers. I know you said you accept that, but I'm noting it since it's no longer occurring in #1251 and #1252, after you reduced the delay.

**Comment by luizaogs** [comment] 2021-11-14 20:54
Deleting an image through the FM menu also leads to its deletion from the gallery here, as it does in #1255.

**Comment by luizaogs** [comment] 2021-11-14 21:00
The rest is all working here.

**Comment by lbestock** [comment] 2021-11-14 22:37
I tested this as written in the wiki, using the blighted black iPad. It all worked as it did for Luiza. Deleting the site note did not remove the images from the gallery, it just removed the site note identifier. Deleting the image through the FM menu did lead to its deletion from the gallery though I note that there is a blank image container at the bottom of the gallery where it should be. Sort of half there.

**Comment by urapadmin** [comment] 2021-11-16 18:39
please try this again with the new FileMaker 19.4

**Comment by urapadmin** [comment] 2021-11-16 19:06
no, need, just tested it: Not fixed in filemaker.The issue prevails.

**Comment by urapadmin** [comment] 2021-12-14 19:40
### @test 11.6.10
- [ ] deletion should work fine now both in the main container and in the popup

**Comment by luizaogs** [comment] 2021-12-14 21:55
Huh. Weird: using the FM menu to delete did preserve the images in the gallery (deleting the identifiers), but I am also getting two empty image containers with the identifiers in the gallery, so it looks like the images were preserved but the old records of those images with the identifiers still have placeholders in the gallery? I deleted one through the main container and one through the popup, and got the same result.

Here's a screenshot (the two images you see are the ones I deleted, and there is another empty container with the PVD identifier below the first one): 

![IMG_0254](https://user-images.githubusercontent.com/67970402/146085196-b4922fe4-f628-4d05-ad0c-020f6645d026.PNG)

**Comment by luizaogs** [comment] 2021-12-14 21:56
Deletion using the "remove" button rather than "delete" in the FM menu still works as it should: image preserved with no identifiers.

**Comment by urapadmin** [comment] 2021-12-14 22:14
please tell me your FM GO and iOS version again

**Comment by luizaogs** [comment] 2021-12-14 22:15
Sorry, I always forget. FM Go 19.4.2.202 and iOS 15.1.

**Comment by urapadmin** [comment] 2021-12-14 22:17
I don't always need it. Just wanted to make sure we are on the same page. We are.

**Comment by urapadmin** [comment] 2021-12-14 22:19
and I can reproduce this all of a sudden.

**Comment by urapadmin** [comment] 2021-12-14 22:27
are we talking about site notes here or the site map?

**Comment by urapadmin** [comment] 2021-12-14 22:34
I know :o) There is just this looming confusion over wether one is in site notes but manipulating the site map instead of images of a site note.

**Comment by luizaogs** [comment] 2021-12-14 22:40
Since images are the bane of my existence and I constantly mess them up you’re right to check :)

**Comment by urapadmin** [comment] 2021-12-15 00:06
In the end it didn't matter at all. I am still running circles. Fixed a hole, another pops up.

**Comment by urapadmin** [comment] 2021-12-15 00:07
### @test 11.6.11
Let's try this one, rather to gather more data. It might work now. But it is a mess and I am about to retreat to a very different line of defense.

**Comment by urapadmin** [comment] 2021-12-15 00:13
we could be back now to the original delete issue in #1255 and here (I think it was that the image got deleted form the gallery)

**Comment by luizaogs** [comment] 2021-12-15 12:51
Hallelujah, habemus deletion. It all worked -- both FM menus in the regular container and the popup, and the non-FM deletion. All images are preserved in the gallery without identifiers and we no longer have empty containers with the old identifiers. 

Should I close it or are both Laurel and I testing all of the tickets?

**Comment by urapadmin** [comment] 2021-12-15 15:12
no, don't close it. If the site map does not work properly, this here might stop working as soon as I try the next thing with the site map. We will go on and test both of these parallel.

**Comment by urapadmin** [comment] 2021-12-15 18:54
### 11.6.12 
Changed an error that should have affected site note images, too. Funny it did not.

- [ ] deletion still good now
- [ ] everything else still working

**Comment by luizaogs** [comment] 2021-12-16 12:35
All working here, too. Yay!

A minor observation: the "insert image or file here" text is missing from the popup in site note images and I think it's usually there elsewhere, but I can't really remember if the popup never had it here or if this is a new development, so I note it.

If the above thing is irrelevant (or if it should go in a new ticket), this one can be closed from my end.

**Comment by urapadmin** [comment] 2021-12-19 20:42
@test 11.6.14
- [ ] There is the "insert image" text and we should be done here.

**Comment by urapadmin** [comment] 2022-01-14 19:24
reopening this because of #1253: a bug affects all containers in a list

**Comment by urapadmin** [comment] 2022-01-14 19:25
### @test 11.6.17
- [ ] please test this again

**Comment by luizaogs** [comment] 2022-01-14 21:36
Still working.

**Comment by lbestock** [comment] 2022-01-14 22:52
Whoops, @mcornacchia25 I forgot to add you to this one last night.
Also, you guys are rad. I am late to the testing party today thanks to letters of recommendation deadlines, but I saw work happening even without me and it was so lovely.

**Comment by lbestock** [comment] 2022-01-14 23:04
Well, I got a 2a. We had a good scream about it in the living room. Blank image containers, viewable if you click on the container and hit view. Not visible if you hit the popup. Do not become visible if you go to a different tab in site notes. Become visible if you leave site notes and re-enter. And I'm up to date on my FM Go and testing in 11.6.17 (I think - we need to change the background color of the PVD banner to make that more visible).

**Comment by mcornacchia25** [comment] 2022-01-14 23:08
Not a bug, but I figured I might point it out as a fresh set of eyes: It took me a minute or two to realize where site notes were located. This is a larger trend where there are a lot of buttons with somewhat unclear images and no labels, which can be confusing for me as I'm not familiar with the software. Maybe an image meaning chart would be a helpful thing to include in the potential future user guide. 

Random strange thing: Anywhere else, if I go to the image gallery from anywhere else, the way to exit is an x that takes me back to the page I was on before. In site notes, it's a home button which takes me back to the home page instead of site notes. 

Otherwise, I haven't had any issues with the image containers.

**Comment by lbestock** [comment] 2022-01-14 23:18
@mcornacchia25 good idea - I made a ticket for an image meaning chart for a user guide. You might get to design it :)

I've put this through the image test as well and no 1s occurred. That's three of us. I think we can close this.

**Comment by urapadmin** [comment] 2022-01-25 00:10
### @test v11.6.18
I reopen this after changes I made because of #1293. 
This needs only a quick new test by one of you to see if it still does what it should. You can close it again if it looks okay.

**Comment by mcornacchia25** [comment] 2022-01-25 00:52
Works for me

**Closed by mcornacchia25** 2022-01-25 00:52 UTC
Labels: bug, test-stage, filemaker
