### ISSUE TITLE
erroneous message that the identifier is unknown

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#696] opened 2020-07-09 00:09 UTC
File repository 0.8.4 on the local server. I had just synchronized, after having made a new locus (and a bunch of other stuff). I searched the file repository for the locus, and got the very funny return that the identifier is unknown but ALSO got the images I should have gotten from the search. Obviously I didn't click 'fetch em so I don't even know what I did to make them appear! Maybe hit return? I think this is related to something we have had before but my brain, it is mush.

![image](https://user-images.githubusercontent.com/49291909/86982303-eade3200-c156-11ea-9f0e-dab50add921c.png)

**Comment by lbestock** [comment] 2020-07-09 00:13
Ja it looks a lot like #651 to me except that now the images are found and it's just the statement about the context being unknown that hangs around. And it is mouse-clicking on that wrong message, as though the message were the correct one, that gets me to the images.

**Comment by urapadmin** [comment] 2020-07-13 22:46
the file import might suffer from the same issue? see #714

**Comment by urapadmin** [comment] 2020-08-01 21:49
in fact this is a duplicate of #651

**Comment by urapadmin** [comment] 2020-09-03 16:51
closed because of duplicate

**Closed by urapadmin** 2020-09-03 16:51 UTC
Labels: bug, duplicate, file-repository
