### ISSUE TITLE
gallery does not refresh properly on open

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#535] opened 2020-04-16 15:06 UTC
when opening the gallery the former filters are still visible and so are the former results. Changes that have happened in the meantime are not reflected in the result set. 
The gallery should repeat the search when opened.

**Comment by urapadmin** [comment] 2020-04-16 19:46
### fixed in v8.9.14

**Comment by SamKimball-BrownU** [comment] 2020-04-22 21:11
Not done testing but ran across this in other testing, was going to make a new ticket. This is certainly the case in the header gallery, but I need to test further. Will update later.

**Comment by SamKimball-BrownU** [comment] 2020-04-30 02:26
aha! it is refreshing now! (v9)

I think my problem was that I didn't understand the actual intended behavior before.

In the gallery accessible from the main menu, the former filter is still applied, but with new results. Any changes are reflected in the results. This is ideal and fully functional.

However, I ran across a bug that is different enough to make its own ticket, #579

**Comment by SamKimball-BrownU** [comment] 2020-04-30 02:30
Given #579 I don't think I can really close this. As far as the main menu gallery, this is functional; in all other galleries, it is not

**Comment by SamKimball-BrownU** [comment] 2020-04-30 02:32
Basically, the issue of updating results with regards to changes made is resolved; however, other issues have appeared

**Comment by urapadmin** [comment] 2020-05-05 20:47
### fixed in 9.0.2
Going to the popover gallery from an "add from gallery" button should now always erase the filters and show all images. 
Going in from the start menu shows the last filter (applied either in the popover gallery or in the start menu gallery) and the correct results of that filter. see #535

**Comment by SamKimball-BrownU** [comment] 2020-05-11 04:25
Resolved

**Closed by SamKimball-BrownU** 2020-05-11 04:25 UTC
Labels: filemaker, test-stage
