### ISSUE TITLE
Cannot access some features in PVD

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#741] opened 2020-07-16 20:32 UTC
F200
F201
F202
F203

It gives popup that says "Error adding a context: The context F200 is already in use. Please enter a unique  value here."

press ok on that one
then another popup that says "Hidden locus was not created"

I can access the other features that Nuri created, as well as everyone else's features/survey units/etc.

Possibly related to #716 ? where some ids were assigned "wrong"

**Comment by lbestock** [comment] 2020-07-16 20:41
This is when you're using the unit selector on the home page, right? This must be because Nuri changed the ID methods so that those numbers were assigned to CONTEXTS not features - those four are the contexts of unit NA1. How do we want to deal with this, or should we? It's very related to #716.

**Comment by urapadmin** [comment] 2020-07-17 13:29
yes, Nuri's NA1 has created F200 already as a locus at some point. There is nothing one can do about it. That's why it is really important that identification methods are well configured. The only possible solution is to give the feature units you try to create a different identification method for loci. But since it cannot be free input it would have to be a method that just eliminates the error that is caused by the false NA1 locus identifiers. We could also just delete NA1 and everything that is attached to it.

**Comment by urapadmin** [comment] 2020-07-17 13:40
as for deleting a unit: #742

**Comment by lbestock** [comment] 2020-07-17 15:31
Should we talk about the conditions under which we would want to delete a unit? In this particular case we would rather rename it than delete it - the numbers are not in step with the rest of the project but the data themselves are fine. We don't even need to get rid of it in a test scenario - it was a valuable lesson and we're not blocked by it, are we?

**Comment by urapadmin** [comment] 2020-07-17 17:36
I think we should not overthink this particular instance. It is apparently in the way of accessing features F200, F201 ... I can as well rename the hidden loci. But as a feature that does not need a developer, so for the field, #742 is the only possibility that clears a problem. Data would have to be typed in again.

**Comment by lbestock** [comment] 2020-07-17 18:23
It isn't in the way of anything - there is no feature F200, just a context F200. That can be accessed as normal through the unit. It's just that F200 shows up as a feature in the unit dropdown from the start page and so appears to be inaccessible, but that's because it doesn't exist as such.

**Comment by urapadmin** [comment] 2020-07-17 18:41
Don't get it. I admit I had too much Riesling yesterday and I am not on top of things, but there are feature units F200, F201, F202, F203... All last modified by Nuri. They are feature units, they have been defined as units and created as unit records. It is the hidden locus that cannot be created now (it would get the same id as its feature unit, I suspect) because there is already a locus of the same name that has been created in NA1 as an excavation locus. Where do these units come from?

**Comment by lbestock** [comment] 2020-07-17 19:17
How is it possible that both a unit and a context were given the same identifier from a single workstation list? Shouldn't that be utterly impossible? And Nuri couldn't have changed the feature identification method to free input, he can't get into configuration. And we know he used the feature numbering function to assign F200 etc to contexts, and that before feature F200 was created (7 July, 10 July, if I read it correctly).

Also I note that I can't see modified by on the unit creation accessed through the gear button on start.

**Comment by urapadmin** [comment] 2020-07-17 19:45
then make a ticket and not a note

**Comment by urapadmin** [comment] 2020-07-17 23:48
That is totally possible. They are different record types. When using an identifier from a numbering list the system looks whether or not that identifier has already been applied as an identifier to a record of that type. And that is not a bug, it is that way on purpose. 
But why have these features been created in the first place if you never intended to have features F200-F20X?

**Comment by lbestock** [comment] 2020-07-19 13:27
Ah, I thought that once used anywhere a number was off the list. Now I understand. It was intended to create features F200-F20X. And those that had numbers other than the numbers previously given to contexts behaved normally as features.

**Closed** 2020-07-23 14:02 UTC
Labels: filemaker
