### ISSUE TITLE
tag analysis not returning photos for tagged features

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#825] opened 2020-08-05 16:51 UTC
Related to  #664, which tested this and found it done so I'm not sure what's up.

I have gone into tag analysis where there are many tags now that have been applied to features. For example the tag S800 Brassil Park Rest Area. No photographs appear here. One CM does - F700-1, but for instance there is a dayplan of F700 and that should appear, too. Nor is F700 the only feature tagged with this tag, so additional photos should appear. 

9.5, looking at it on laurel's mac.

**Comment by luizaogs** [comment] 2020-08-05 18:05
Sorry to butt in but I saw this when looking up another ticket just now and was curious because I struggled with images for feature relationships in this assignment (see my long rambling in the day 3 issues page if you're interested). The current tagging is of collected material only, so in #664 I was testing if images of collected materials of features showed up, not dayplans. Which is why I was wondering if that would need to be changed if tags are indeed the way to go for feature relationships in the future. 

Ok, butting out now.

**Comment by urapadmin** [comment] 2020-08-05 18:25
the photographs don't appear because they are dayplans. Since we are tagging loci and not dayplans and you do not attach images to the hidden locus those images do not appear. Quite like the dayplans of an excavation unit do not appear because you tagged locus. It is just that there it is more obvious to you from the way you've been using it.

No question, this is not optimal from a user's perspective but that is what locus tagging can do so far. It is not a bug. 
Everything else must be tackled here: #669. This is again one of the merits from having a hierarchical data structure :o(

**Comment by urapadmin** [comment] 2020-08-05 18:27
strange how this whole project shifted towards features. I think that has a lot to do with the "un"-nature of it. Features were never such a thing before.

**Comment by urapadmin** [comment] 2020-08-05 18:30
> 
> 
> .. .Which is why I was wondering if that would need to be changed if tags are indeed the way to go for feature relationships in the future.
> 

I really think using tags to create feature relationships on the scale you've been doing it here cannot possibly be a good way. If feature relationships are really a thing you guys should sit down and define them. First of all I suppose they should be bi-directional as the locus relations. And that is already a reason not to use tags.

**Comment by luizaogs** [comment] 2020-08-06 11:27
I think it was definitely decided that tags are not the way to go for this. Laurel, should I close this and start a discussion ticket for that? Or is that something that would now go in the wiki...?

**Comment by urapadmin** [comment] 2020-08-30 10:11
@lbestock: ?

**Comment by lbestock** [comment] 2020-08-30 23:08
We should document in the wiki the nature of our PVD experiment and what we ran into, but we have **definitely** decided tags as they currently exist (and probably beyond) are not the way to do feature relations. And we have NOT decided if feature relations are in fact a necessary thing at all, and we will not try to decide that until a project that uses features in survey says they need that and explains to us why and how in an actual archaeological situation.

The only reason I am still reluctant to close the ticket is because of the legacy data issue: features are how we get Wheeler's stuff into the recording system. The whole point of that is to be able to consider his stuff alongside ours. One point of that is collected material - possibly the main point - which would already be captured. However, are tags really the way to do this even here? (Allow me to think "aloud" - sorry.) At first I thought "that is a mess, think of Unit FA/Room 5 - Wheeler's Room 5 is now a feature, we can tag it. But to pull that up with everything else would mean to tag EVERY locus in FA "Room 5", too, and that's bonkers, and then also I only get the CM and not his notes, etc." But then I thought "Yeah but that's a weird unit, where the room and the unit are contiguous. Think of FI, where in fact you already have tagged loci as belonging to rooms because there are three rooms in the uint."

So, leave this please. I will look at FA and FI in URAP and comment more intelligently later - I know this isn't a bug and could be closed for that reason, but I don't want to lose it.

**Comment by urapadmin** [comment] 2020-08-30 23:17
why not summerize the issue in an intelligible way and put it in the wiki? Tickets are not the place to work on concepts. They become a mess.

**Closed** 2020-08-30 23:45 UTC
Labels: filemaker, needs discussion
