### ISSUE TITLE
hitting "view" on a locus relations image immediately after creation brings up the project's logo

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#727] opened 2020-07-14 17:41 UTC
Tiniest of funny bugs. 

In Filemaker V.9.4, my trial run being on PVD2020. When one creates a locus relationship image and then clicks on the image itself so that one is given the options "view, replace, export, delete", if one clicks view one usually then views the image. And this happens to this image in this container USUALLY. But not always - if one does it immediately after creating it, before one has clicked anywhere else, one gets instead the project logo. Funny! (And in fact in repeating my steps I note one is encouraged to do that because the "view, replace, etc" dialog box opens automatically after one has made a locus relation image, and that is when this happens, it involves no clicking on the image to call up that dialog in the first place.)

What the screen looks like just after I made my image, including the automatically popped up dialog box:
![image](https://user-images.githubusercontent.com/49291909/87458115-77657600-c5d7-11ea-8ef0-3fb5e0e488e1.png)

What happens if I press view:
![image](https://user-images.githubusercontent.com/49291909/87458168-919f5400-c5d7-11ea-8e56-02addb77a2c3.png)

**Comment by nvd2** [comment] 2020-07-26 19:41
The same problem has happened to me a few times in testing so I'm moving it back to developer.

**Comment by urapadmin** [comment] 2020-07-26 22:27
Good to know that the issue can be easily reproduced.
But I am also puzzled. I have never attended to it and it has never been in the testing project (nor is it currently in there in "back to developer").

**Comment by urapadmin** [comment] 2020-07-28 12:07
filemaker and the field order. A neverending story. It is just that after inserting the image in the locus relation filemaker hops to the next element which is accidentally the logo and opens the context menu there because it is an image.

### 9.4.5
I have taken that logo out of the tab order. But who knows where filemaker Go will hop to next.

**Comment by nvd2** [comment] 2020-07-29 16:26
I was not able to replicate it again when I tried it. Now when you click on view after adding an image it shows you that image.

**Closed by nvd2** 2020-07-29 16:26 UTC
Labels: bug, filemaker, small, test-stage
