### ISSUE TITLE
QR code recognition upload failed

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#627] opened 2020-05-17 18:40 UTC
Testing file upload on URAP 0.7.3.

Attempted to import photos with prominent QR codes for known contexts. Tried both Sahara and Black Velvet. None of the photos were imported and the failure was quite quick. Been so long since I did this that I am not entirely sure I have remembered properly how to run this, but I did just have success with importing with context grabbed from exif data.

**Comment by lbestock** [comment] 2020-05-18 01:13
I had an idea that the problem recognizing QA as a context might be behind this. Lutz was skeptical. The cache reset means that QA is now recognized, but the file upload failed again on all photos.
Here is one - the issue cannot be an illegible QR code.

![image](https://user-images.githubusercontent.com/49291909/82165500-442a9300-9883-11ea-9b1f-3b6f2ed374f6.png)

**Comment by lbestock** [comment] 2020-06-19 22:42
Have had a failure on this front again, only this time it was not quick - it clearly tried. The new case of failure:

I made new records in USTP including a context 695. Synchronized. (Failure in kiosk for 695 to be a recognized context before forking will be a separate ticket momentarily.) Did a QR code import of two NEFs. It took its time thinking about them, then gave me this:

<img width="1427" alt="Screen Shot 2020-06-19 at 5 52 02 PM" src="https://user-images.githubusercontent.com/49291909/85184051-4ace7080-b25c-11ea-8e40-a83f31d49fb1.png">

We thought of the cache problem and so forked and made sure that 695 was a recognized context and then tried the import again, but same problem.

I was generally entering records for USTP and thought to do this in part to address #649; the images were created from within CM records that have the same apparent identifier since USTP has no real CM numbers. But the first is from a bones record and the second a ceramics record and it'd be nice to see them ending up in the right place.

The images that failed are attached here as jpgs because github does not support NEFs; if needed, the original NEFs are in the shared dropbox recording system > Candace. 
![DSC_0047](https://user-images.githubusercontent.com/49291909/85184031-368a7380-b25c-11ea-93f5-710f22e8fbfa.jpg)
![DSC_0048](https://user-images.githubusercontent.com/49291909/85184034-37230a00-b25c-11ea-835c-7b4c6f17cfcd.jpg)

**Comment by lbestock** [comment] 2020-06-19 22:55
[Archive.zip](https://github.com/urapadmin/kiosk/files/4806938/Archive.zip)

**Comment by urapadmin** [comment] 2020-07-04 13:23
see also #649

**Comment by urapadmin** [comment] 2020-07-06 21:19
funny I did not even get that error message with jolly jobber anymore. So first I had to debug a lot to get an error message all the way back to that dialog. And quite a way it is. Strange that that ever worked. 
But is is clear that the context is read correctly from the qr code (it was 695). So the question is: Why is the identifier unknown?

**Comment by urapadmin** [comment] 2020-07-07 14:54
and now that I tested it against the ustp_test database, it works. So it must have been a cache issue. 
It might not reoccur because I have attended to #651 meanwhile. Please test again.

**Comment by urapadmin** [comment] 2020-07-07 14:56
### can't repeat
works on the ustp_test server on Beset as well. 
- [ ] Please test if importing a file for a just synchronized identifier works as well.

**Comment by lbestock** [comment] 2020-07-15 15:44
LDB: write QR code photography into next day scenario testing to enable us to test this.

**Comment by lbestock** [comment] 2020-07-22 16:02
Attempting to do this myself before a team meeting, I am still not able to. I checked in the file repository - there are already images for this context in there. I was trying to do PBA-004 on PVD2020 online Beset. That context is old and has been through multiple synchronizations.

![image](https://user-images.githubusercontent.com/49291909/88199415-d5ffa500-cc12-11ea-9f9e-157a5037c778.png)

What you see in the background is the file repository showing images from the context in question. 

The file in question:
[DSC_0016.NEF.zip](https://github.com/urapadmin/kiosk/files/4961054/DSC_0016.NEF.zip)

**Comment by lbestock** [comment] 2020-07-22 16:03
OH WAIT. I just saved that as a jpg and tried it again and this time it worked. So there's something about the NEF. The only other variable is that the NEF I was trying to import straight off the SD card and the jpg was saved to my desktop.

**Comment by lbestock** [comment] 2020-07-22 16:07
And now I can say definitively that the file type is the issue, having successfully uploaded QR jpgs from the same SD card.

**Comment by urapadmin** [comment] 2020-07-22 19:42
if you don't add your time I don't know where in the logs to look for such errors! The time is crucial!

**Comment by lbestock** [comment] 2020-07-22 19:56
I did on the new ticket I made about it! Was just after noon on 22 July 20.


Laurel Bestock
Associate Professor of Archaeology and Egyptology
Director of Graduate Studies, Joukowsky Institute for Archaeology and the
Ancient World
Brown University

https://blogs.brown.edu/archaeology/fieldwork/uronarti/

**Comment by urapadmin** [comment] 2020-07-22 20:08
Github glitch. I deleted this complaint immediately after I wrote it 
because in fact the error message gave me the exact logfile. But you 
already got the email.

So don't write "you bloody fool" and then delete it. Won't help.

Am 22.07.2020 um 21:56 schrieb lbestock - notifications@github.com:

**Comment by urapadmin** [comment] 2020-07-22 21:02
I can confirm that. OpenCV cannot open NEFs and that's the image manipulation library we are using. I have to convert the raw files first. 
Please test using converted jpgs for a while, I want to wait for the other raw images (Canon / Olympus) before I open this can of worms again.

**Comment by urapadmin** [comment] 2020-07-22 21:03
I suggest we close this, because I do think that it has been the file format issue from the very beginning.

**Closed** 2020-08-30 11:50 UTC
Labels: A: next!, bug, file-repository, kiosk, test-stage
