### ISSUE TITLE
"none" instead of "nope" when turning off simple excavation

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#764] opened 2020-07-23 00:17 UTC
We're back to Luiza's picky notes, hello and welcome.

Just turning off simple excavation to test the pinboard and I know the instructions should say "nope" but they say that one should write "none" to turn that off instead:

![image](https://user-images.githubusercontent.com/67970402/88241397-fd2c9580-cc57-11ea-83a7-68b9f0c6ad1f.png)

**Comment by urapadmin** [comment] 2020-07-23 10:24
### fixed 9.4.2

**Comment by luizaogs** [comment] 2020-07-24 20:38
Hmm this is still coming up as "none" for me.

**Comment by urapadmin** [comment] 2020-07-24 21:26
I am not surprised and should have announced it. Wait another round of synchronization. It should be there then. It travels a bit slower than other things I update.

**Comment by luizaogs** [comment] 2020-07-24 21:54
Ah I see. Will move it back to testing and wait until then!

**Comment by luizaogs** [comment] 2020-07-27 13:43
It's still there in 9.4.4. Mainly a note to myself so I remember to check again after the next update (unless you think the modification should have already showed up, Lutz?).

**Comment by urapadmin** [comment] 2020-07-28 10:17
there are in fact several things not right. use_simple_excavating should be under "visibility" and I have double checked that it is patched so from my point of view it should have been there in 9.4.4. Hm. That is hard to trace because it travels through so many steps. I cannot say if the workstation that got the original patch has been synchronized. Otherwise the patch would not make it to the main database. 

While the instance itself is not crucial a failure of the patching mechanism is more severe. We should keep an eye on it and perhaps give it another round of intense ticket testing. Next milestone.

**Comment by luizaogs** [comment] 2020-07-28 10:36
Under "visibility"? I only see it under "general"?

But yes I'll check again after synchronizing next time and keep you updated.

**Comment by urapadmin** [comment] 2020-07-28 11:03
### 9.4.5
found it. One of the more interesting bugs. 

That you see it under "general" is a symptom of the same error that kept configuration updates from being applied at all. When the update gets applied it will change the "none" issue but also move the configuration key to "visibility".

Although 9.4.5 fixes this, note that after you got 9.4.5 for the first time it might still look the same. Only after the next round of synchronization it should definitely have reached you. The strange traveling of such updates is by design.

**Comment by urapadmin** [comment] 2020-07-28 11:04
also please note that noticing what seems to be merely a picky thing can reveal a serious bug. So keep your eyes open :o)

**Comment by luizaogs** [comment] 2020-07-28 11:13
I really can't control my pickiness so eyes will definitely be staying open :) I'll let you know once it comes through!

**Comment by luizaogs** [comment] 2020-07-28 20:25
Looking good now (both the visibility and nope issues)!

**Comment by urapadmin** [comment] 2020-07-28 22:10
fine. But also means: You got the first update and should have seen the "you got an update" message on the start screen after logging in to filemaker. It also means you should make sure you upload your workstation and then somebody needs to test if after the next synchronization it is still ok.
So I reopen this.

**Comment by luizaogs** [comment] 2020-07-28 22:14
I don't think I did. @SamKimball-BrownU didn't you say you had 9.4.6 in the meeting before everyone else got it?

**Comment by SamKimball-BrownU** [comment] 2020-07-28 22:16
Yep, the patch rolled out to me first. So, maybe it would be valid to test now? Updates are still one of the things that I do not fully grasp.

**Comment by urapadmin** [comment] 2020-07-28 23:05
configuration patches, as I call them, are really special. One has to understand first that configuration keys are synchronized in a project like all other data. For me as a developer that is a problem because how can I feed a configuration change into such a synchronizing system without being part of the synchronization myself? This is how:
1. I set a configuration key (it consists of the key, the value but also of the help text and the category) in the development template to "patch". 
2. Only the first workstation that is prepared on the basis of that template gets those "patches". 
3. when the user opens that workstation the patches are turned into real configuration keys: This is when my changes are actually applied to a configuration. This step is as if a user would have changed those config keys manually - they are changes from the perspective of the synchronizing system.
4. and that is why this workstation needs to be uploaded and synchronized, because otherwise the patch would not enter synchronization.
5. in synchronization the changes are handled like all changes to the configuration: If nobody else has made more recent changes, they will be applied to the master database. 
6. And that is why my original change to a configuration key reaches ALL workstations only after a synchronization and fresh preparation of all of them.

**Comment by urapadmin** [comment] 2020-07-28 23:08
Luiza, if you were not the one who got the first 9.4.6 and hence were greeted with the update message, then I am a bit surprised that you already got the changes. It is always possible that I don't remember all the details, but according to my explanation you should have gotten the changes only after synchronization ...

**Comment by urapadmin** [comment] 2020-07-28 23:09
remember: This is not about who downloaded first! This is about whose workstation was prepared first!

**Comment by urapadmin** [comment] 2020-07-28 23:14
@luizaogs: And this is also your answer for #782: The orange configuration keys are marked as being "patched". So they will always be set to what I defined in the developer template as long as they are marked as patches.

**Comment by luizaogs** [comment] 2020-07-28 23:31
If Sam had 9.4.6 before the meeting his workstation was definitely prepared first because mine was still set to "in the field" until the end of the meeting, when Laurel prepared everyone's downloads. 

I do remember getting that update message -- I think it was yesterday when I was the first person to get 9.4.4. But no one told me that I needed to synchronize it and since I only had nonsense data I never uploaded it, but I just checked and the 9.4.4 changes I had tested in that one are still fine. Is that normal?

**Comment by urapadmin** [comment] 2020-07-28 23:56
no one told you? Ha! The message told you! 
(users don't read my messages or don't take them seriously).
But apart from that now I am really at a loss as to why you can see those changes before the first workstation got synchronized. Hm. (The Riesling and Corona also make me think of my patch mechanism as a virus). 
I'll look into it again, tomorrow, but I have a hunch we should test this configuration key updating mechanism isolated after we reached milestone 9.5.

**Comment by luizaogs** [comment] 2020-07-28 23:58
Yeah yeah I knew you were going to say that :) I remember reading it and then Laurel asked me if I needed to upload it after the meeting and I was like nah. Sorry! I promise I read them but then I also forget them.

**Comment by urapadmin** [comment] 2020-07-29 00:03
I should rhyme my messages (helps with memorizing them). Or give them an irresistible metre. But then if I could do that, I think I would quit and be a poet :o)

**Comment by luizaogs** [comment] 2020-07-29 00:32
Here's a really great haiku:

hey, you got a patch
so — bogus data or no — 
upload it you must

Yes, I'm a poet.

**Comment by lbestock** [comment] 2020-07-29 02:40
Tracing the configuration patch virus would need an army of specialist contact tracers this round, and would run into the problem of forgetful carriers. I have been resetting devices like a madwoman as people test and create spurious data and new versions come out. It is true I asked Luiza if she needed to upload, but I had forgotten about the possibility of a patch and so I suspect I said more something like "did you add new data?" which is not quite the same question. Same with Sam, whom I reset at least twice. It's a bit funny to observe that the patch is both more likely a factor in the frenetic environment of testing but also more likely then to be missed.

**Comment by SamKimball-BrownU** [comment] 2020-07-29 02:53
> no one told you? Ha! The message told you!
> (users don't read my messages or don't take them seriously).
> But apart from that now I am really at a loss as to why you can see those changes before the first workstation got synchronized. Hm. (The Riesling and Corona also make me think of my patch mechanism as a virus).
> I'll look into it again, tomorrow, but I have a hunch we should test this configuration key updating mechanism isolated after we reached milestone 9.5.

For the record, the message that I got was the only reason I decided to actually upload my data! So, in that sense, it worked as intended. 

There was also a point where I had to prepare for download again in order to get 9.4.6. Perhaps that was a contributing factor?

**Comment by urapadmin** [comment] 2020-07-29 11:14
This is a mess at this point and I suggest we close it. As far as I can see the issues at hand are fixed and should we get the feeling again that config patching is unreliable we take it into the lab and test it in a more clinical test.

**Closed by urapadmin** 2020-07-29 11:14 UTC
Labels: bug, filemaker, small, test-stage
