### ISSUE TITLE
feature recording: filemaker shows blank panel over UI after inserting an image (error type 1)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1251] opened 2021-11-12 17:24 UTC
next image container: feature recording. We are talking about the tree-housish feature recording here.

my todo:
- [x] develop add_*_to_cache_deferred method
- [x] change primary image container to add_*_to_cache to add_*_to_cache_deferred
- [x] change sec. image container to add_*_to_cache to add_*_to_cache_deferred
- [x] change image_gallery_select_image to using add_*_to_cache_deferred
- [x] change method behind description field to using add_*_to_cache_deferred

**Comment by urapadmin** [comment] 2021-11-12 17:26
### recording 11.6.2
- [ ] test according to schema

**Comment by luizaogs** [comment] 2021-11-13 17:44
When adding a new image in the popup (not through the gallery) I get this menu in between flickers - it disappears after another flicker but is there for a split second. Is that ok?

![F725C5FE-0006-4485-A36F-830D8B1FA4F1](https://user-images.githubusercontent.com/67970402/141653718-1a78f554-7f98-48eb-a505-32293cfbf73a.png)

**Comment by luizaogs** [comment] 2021-11-13 17:52
Everything else here is fine, so if the above is fine this can be closed.

**Comment by luizaogs** [comment] 2021-11-13 18:40
Ah and when adding the image in the normal image container I get a flash of the keyboard but it goes away.

**Comment by urapadmin** [comment] 2021-11-13 21:11
well, if it is okay or not is a matter of perspective. It is at least a side effect of delaying the update of the file identifier cache. The one that caused all the trouble when I was doing it while adding the image. Now there is a second between inserting the image and updating the cache. And in that second filemaker does what would have been the result of the operation as a whole before.
So here in locus photos at the end of inserting the image AND updating the file identifier cache in one operation the menu would have been visible (unless error type 1 would occur).
Now the menu gets visible after inserting the image. And then after the second the update of the cache leads filemaker to refresh and close the menu (or the keyboard or whatever is open).

I am not sure what is better? I even thought that it might be an improvement that neither the menu nor the keyboard stays visible after inserting an image?

What do you think? 
And you, @lbestock?

**Comment by luizaogs** [comment] 2021-11-14 02:41
Ah I see. Yes, I think I personally prefer to have it flash and disappear rather than ending on either the menu or the keyboard and having to close it myself.

**Comment by luizaogs** [comment] 2021-11-14 19:46
This is all working as well, and I no longer see flashing keyboards or menus. Do we close it?

**Comment by luizaogs** [comment] 2021-11-14 19:56
Dammit. Dammit. Error 1. I went back to check something and added a dayplan, and:

![IMG_0241](https://user-images.githubusercontent.com/67970402/141696418-6d61af47-852c-428b-b060-2928202c3038.PNG)

**Comment by urapadmin** [comment] 2021-11-14 21:42
so you did not have to close filemaker? You just switched to a different app and when you came back the panel was gone?

**Comment by luizaogs** [comment] 2021-11-14 22:11
Yes, double clicking and moving to Photos, then coming back got rid of it.

**Comment by urapadmin** [comment] 2021-11-15 00:05
This is not typical for a type 1 error, is it? In my cases the panel would not go away until I close filemaker.
Can you reproduce it?
@lbestock: please note.

**Comment by lbestock** [comment] 2021-11-15 00:34
This is all working for me. The flashing menu is a super brief flash (how did you even get a screenshot of that, @luizaogs?) I definitely prefer having an action end with no menus or keyboards at all, by a long shot. If it means suffering a brief flash of one in between that's fine (also - not the way I usually insert images, and the standard non-popup way doesn't have this). 

I have not been able to reproduce the not typical type 1 error or any other error yet with this one. And again I'm testing on the blighted black iPad.

**Comment by luizaogs** [comment] 2021-11-15 02:30
That screenshot was from yesterday. Today I get no flashing menus any longer, I think because of the new timing on the flickers.

I just got the blank screen again, adding a dayplan in the normal image container (rather than the popup). But yes, simply clicking out of FM to another tab or the iPad home screen and then double tapping again and coming back leads to the image being where it should be; I cannot really remember if that was the case for error 1s previously. I do not think I can reproduce it reliably -- when I get it I am doing nothing differently than when I do not get it.

**Comment by luizaogs** [comment] 2021-11-15 02:49
I don't know if this is helpful or consequential in the slightest, but I turned the iPad from landscape to portrait to see if I could get a screenshot of the error 1 (?) blank screen in this mode and the flickering in portrait seems ... slower somehow? I see a gray screen in the background for a while, rather than the very quick flickering that I get in landscape, and the screen looks very much like the error 1 screen.

I recorded the screen (impossible to get a screenshot) but the file is too big to attach here, so I'll email it to you.

**Comment by urapadmin** [comment] 2021-11-15 18:40
no, I don't know anything. I am just hypothesizing, even about the spelling of that very word. 
This does not look like a type 1 to me. It is rather a type 1b. Great. We develop a whole taxonomy here.

- If it happens again, please send me the log (after you switch back to fm you should be able to open it)
- do you ever get it in either site map or site note photos? I ask, because those are still on the one second delay.

**Comment by urapadmin** [comment] 2021-11-15 18:44
@lbestock: Laurel, I suspect you are still testing with a file picking database, right?
Luiza has gotten this, at least it seems, with a database that has images (or you have created quite a few). 

Is it possible that this gets more likely with more photos or some such?

**Comment by luizaogs** [comment] 2021-11-15 18:48
This is totally a file picking database, I just added a zillion images while trying to get the error. I’ll try to get you a log soon. And no, so far I have only seen this here but will try the site notes/map again.

**Comment by luizaogs** [comment] 2021-11-15 18:56
add_dayplan_to_cache_deferred: single image with param OnObjectModify, $$cache_done=0
add_dayplan_to_cache_deferred: image missing: 0/1
is_cache_update_needed: image is there in OnObjectModify but record is not-> DONT process cache
add_dayplan_to_cache_deferred: doing nothing.
image_validate: field img
add_dayplan_to_cache_deferred: single image with param , $$cache_done=0
add_dayplan_to_cache_deferred: image missing: 0/0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_dayplan_to_cache_deferred: cache update needed.
add_dayplan_to_cache_deferred: cache update timed.
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context dayplan/4D09FEDF-6A96-4F3F-84B4-87D58A84301E
execute_deferred_cache_operation: deleted cache entries.
execute_deferred_cache_operation: added image to cache with identifier F041
closed temp window  temp_window.
switch_off_menu: Switched the menu off. isMasterDb = nope

**Comment by luizaogs** [comment] 2021-11-15 19:01
Just added 20 images in site notes and did not get a 1b, but who knows really since it appears to come and go as it pleases.

**Comment by urapadmin** [comment] 2021-11-16 18:40
well, you may give it another try with FM GO 19.4

**Comment by luizaogs** [comment] 2021-11-17 02:32
iOS 15.1, 11.6.8, FM 19.4.1.31

Yep, got it again. Error 1 this time, it seems, because double tapping out of FM was no longer enough -- I had to close it and open it again. Once that happened the image was there.

**Comment by luizaogs** [comment] 2021-11-17 02:36
Oh wait I can't get the log for this one since I need to log out of FM and come back in, can I? This is the log I get after logging in again: 

switch_off_menu: Switched the menu off. isMasterDb = yup
close_temp_window  temp_window was not open to begin with.
close_temp_window  temp_window was not open to begin with.
switch_off_menu: Switched the menu off. isMasterDb = nope
close_temp_window  temp_window was not open to begin with.
close_temp_window  temp_window was not open to begin with.
close_temp_window  temp_window was not open to begin with.
switch_off_menu: Switched the menu off. isMasterDb = nope
switch_off_menu: Switched the menu off. isMasterDb = nope

**Comment by luizaogs** [comment] 2021-11-17 02:56
Perhaps of note is that I just added at least 20 locus relations images across different loci and did not get the error 1 (or 1b) at all. This is the only place where I have encountered it, even though it is not the only place with the modified delay.

**Comment by urapadmin** [comment] 2021-11-17 10:33
> 
> 
> iOS 15.1, 11.6.8, FM 19.4.1.31
> 
> Yep, got it again. Error 1 this time, it seems, because double tapping out of FM was no longer enough -- I had to close it and open it again. Once that happened the image was there.
> 
> I failed to get a log because I always forget to start in test mode. Hang on...

you are right. No log for real type 1 errors. When you leave filemaker the log is gone.

**Comment by lbestock** [comment] 2021-11-17 13:47
add_dayplan_to_cache_deferred: single image with param OnObjectModify, $$cache_done=0
add_dayplan_to_cache_deferred: image missing: 0/1
is_cache_update_needed: image is there in OnObjectModify but record is not-> DONT process cache
add_dayplan_to_cache_deferred: doing nothing.
image_validate: field img
add_dayplan_to_cache_deferred: single image with param , $$cache_done=0
add_dayplan_to_cache_deferred: image missing: 0/0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_dayplan_to_cache_deferred: cache update needed.
add_dayplan_to_cache_deferred: cache update timed.
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context dayplan/218AA064-9C77-4E9B-9F4C-32EF066A415C
execute_deferred_cache_operation: deleted cache entries.
execute_deferred_cache_operation: added image to cache with identifier F416
closed temp window  temp_window.
switch_off_menu: Switched the menu on. isMasterDb = yup

**Comment by urapadmin** [comment] 2021-11-17 17:51
The logs always look absolutely according to plan, no matter what error we encounter. This is really just contingent behaviour on the fm go side. Not measurable, nothing going wrong, just happens beyond my control and all I can do is flap different butterfly wings to give the chaos a different spin.

**Comment by urapadmin** [comment] 2021-11-17 17:53
An error 3 is really benign and heals itself. Unless we encounter it constantly or massively in a certain place I propose we ignore it.

**Comment by urapadmin** [comment] 2022-01-12 17:16
### @test
@lbestock , @mcornacchia25 , @luizaogs 
I am not sure where we stand here. 
- Who can reproduce the error type 1 / 1b and how reliable does it occur? (We ignore the 3 unless it happens almost always)
- If it occurs, please report how many other apps were open in the background. 
- On those devices where it does happen, does it happen as well in dayplans of a regular excavation unit (simple or full excavation)

**Comment by luizaogs** [comment] 2022-01-12 20:11
Is this the delayed version yet? I've lost track. I am getting the flashing keyboard when using the image container and the flashing keyboard when using the popup but do not get them in dayplans so something seems different.

No error 1s (or errors of any kind) to report - I tested it both with no other apps in the background and a zillion other things running.

**Comment by luizaogs** [comment] 2022-01-12 20:13
Deletions are working correctly. 

A weird thing about changing descriptions, though: I tried changing it for two images and those did not change in the gallery. Then I added a bunch more images to try and provoke errors and added some more descriptions and those I can change and they change properly in the gallery as well -- going back to the ones that had not worked and changing them again works now, too. So basically something was going on and I cannot provoke it again currently but am noting it here in case someone else wants to see if pops up as an issue for them, too.

**Comment by urapadmin** [comment] 2022-01-14 17:29
### @test 11.6.17
We have to test this again from scratch because of a bug I found. There should be exactly ONE flicker and all should work, of course.

**Comment by urapadmin** [comment] 2022-01-14 17:33
> Is this the delayed version yet? I've lost track. I am getting the flashing keyboard when using the image container and the flashing menu when using the popup but do not get them in dayplans so something seems different.

Yess, this is the delayed version. 1 delayed flicker expected.

**Comment by urapadmin** [comment] 2022-01-14 17:45
> A weird thing about changing descriptions, though: I tried changing it for two images and those did not change in the gallery. Then I added a bunch more images to try and provoke errors and added some more descriptions and those I can change and they change properly in the gallery as well -- going back to the ones that had not worked and changing them again works now, too. So basically something was going on and I cannot provoke it again currently but am noting it here in case someone else wants to see if it pops up as an issue for them, too.

I do make this a new issue, though:

**Comment by urapadmin** [comment] 2022-01-14 18:03
### @test 11.6.17
We have to test this again from scratch because of a bug I found. There should be exactly ONE flicker and all should work, of course.
- [ ] Also, I attended to what was indeed still slightly different between dayplans and feature recording photos: The keyboard flashing should be the same as in dayplans. (Same goes for survey unit photos). They should behave similarly.

**Comment by luizaogs** [comment] 2022-01-14 20:57
All is working for me here.

**Comment by mcornacchia25** [comment] 2022-01-14 22:04
It's working for me too.

**Comment by lbestock** [comment] 2022-01-14 23:36
Works for me, too.

**Closed by lbestock** 2022-01-14 23:36 UTC
Labels: bug, test-stage, filemaker
