### ISSUE TITLE
new test_mode for filemaker recording

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#522] opened 2020-04-12 16:36 UTC
a new constant test_mode allows buttons to appear that can help in testing. The first two tools will be: a image-identifier-cache inspector on the start and a button that makes the invisible locus visible in feature and survey units.

**Comment by urapadmin** [comment] 2020-04-12 16:37
### @test: v.8.9.12
The new buttons should be there and they should only appear when test_mode is set to "yup" in confguration/admin.

**Comment by SamKimball-BrownU** [comment] 2020-04-15 03:30
So it seems to be working as intended, but I could use an explainer on what the hidden locus should be/what it represents

**Comment by urapadmin** [comment] 2020-04-15 14:47
Laurel wrestles with the hidden locus in #420. I started an explanation of the hidden locus here: https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:filemaker_recording_-_hidden_locus. Hope that helps or does it lead to more questions?

**Comment by SamKimball-BrownU** [comment] 2020-04-15 20:50
Nope that pretty well explains it! I'm pretty confident that I can close this ticket, but I'm going to assign it to prof. beefstock so that she can close this when she get's around to #420

**Comment by SamKimball-BrownU** [comment] 2020-04-15 20:51
(just to make sure I'm not missing anything about the hidden loci)

**Comment by SamKimball-BrownU** [comment] 2020-05-11 04:43
@lbestock could you just take a quick look at this and close it if you think it's resolved; I am almost 100% sure it is, but I don't know if it is showing the "right" hidden loci. It certainly does show the hidden locus number, but just want to double check that it is correct.

**Closed** 2020-05-17 02:27 UTC
Labels: enhancement / extension, filemaker, needs discussion, test-stage
